/**
 * Recommendations.jsx — Actionable AI recommendations
 */

import { motion } from 'framer-motion';
import { Lightbulb, ChevronRight } from 'lucide-react';

const RECOMMENDATION_ICONS = ['💬', '💕', '⚡', '🌱', '🤝', '✨', '🔥'];

export default function Recommendations({ recommendations = [] }) {
  if (!recommendations.length) return null;

  return (
    <motion.div
      initial={{ opacity: 0, y: 30 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }}
      className="glass rounded-3xl p-6 md:p-8"
      style={{ border: '1px solid rgba(139,92,246,0.15)' }}
    >
      <div className="flex items-center gap-3 mb-6">
        <div className="w-10 h-10 rounded-xl bg-purple-500/10 border border-purple-500/20 flex items-center justify-center">
          <Lightbulb size={18} className="text-purple-400" />
        </div>
        <div>
          <h2 className="font-display font-bold text-lg text-white">AI Recommendations</h2>
          <p className="text-white/30 text-xs">Personalized guidance for a stronger bond</p>
        </div>
      </div>

      <div className="flex flex-col gap-3">
        {recommendations.map((rec, i) => (
          <motion.div
            key={i}
            initial={{ opacity: 0, x: -20 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true }}
            transition={{ delay: i * 0.08, duration: 0.4 }}
            whileHover={{ x: 4, transition: { duration: 0.15 } }}
            className="flex items-start gap-4 p-4 rounded-xl bg-white/2 border border-white/5 hover:border-purple-500/20 hover:bg-purple-500/5 transition-all duration-200 cursor-default group"
          >
            <span className="text-xl flex-shrink-0 mt-0.5">
              {RECOMMENDATION_ICONS[i % RECOMMENDATION_ICONS.length]}
            </span>
            <p className="text-white/70 text-sm leading-relaxed flex-1">{rec}</p>
            <ChevronRight
              size={14}
              className="text-white/10 group-hover:text-purple-400/50 transition-colors mt-0.5 flex-shrink-0"
            />
          </motion.div>
        ))}
      </div>

      <div className="mt-6 px-4 py-3 rounded-xl bg-purple-500/5 border border-purple-500/10 text-center">
        <p className="text-white/30 text-xs">
          These insights are generated by AI and meant as reflective guidance — not relationship advice.
        </p>
      </div>
    </motion.div>
  );
}
